//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odev1
{
    using System;
    using System.Collections.Generic;
    
    public partial class hakem
    {
        public long hakem_id { get; set; }
        public string hakem_adi { get; set; }
        public string hakem_soyadi { get; set; }
        public string hakem_turu { get; set; }
        public string hakem_classman { get; set; }
        public string hakem_bolge { get; set; }
    }
}
