//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odev1
{
    using System;
    using System.Collections.Generic;
    
    public partial class sporsalonu
    {
        public sporsalonu()
        {
            this.takim = new HashSet<takim>();
        }
    
        public long s_id { get; set; }
        public string s_adi { get; set; }
        public string s_sehir { get; set; }
        public long l_id { get; set; }
        public string ozellik { get; set; }
    
        public virtual lig lig { get; set; }
        public virtual ICollection<takim> takim { get; set; }
    }
}
