//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odev1
{
    using System;
    using System.Collections.Generic;
    
    public partial class lig
    {
        public lig()
        {
            this.sporcu = new HashSet<sporcu>();
            this.sporsalonu = new HashSet<sporsalonu>();
            this.takim = new HashSet<takim>();
        }
    
        public long l_id { get; set; }
        public string l_adi { get; set; }
    
        public virtual ICollection<sporcu> sporcu { get; set; }
        public virtual ICollection<sporsalonu> sporsalonu { get; set; }
        public virtual ICollection<takim> takim { get; set; }
    }
}
