//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odev1
{
    using System;
    using System.Collections.Generic;
    
    public partial class musabaka
    {
        public long id { get; set; }
        public string ev_sahibi { get; set; }
        public string misafir { get; set; }
        public string salon { get; set; }
        public string hafta { get; set; }
        public string lig { get; set; }
        public string bas_hakem { get; set; }
        public string yardimci_hakem { get; set; }
        public string yazi_hakemi { get; set; }
        public string cizgi_hakem1 { get; set; }
        public string cizgi_hakem2 { get; set; }
    }
}
